apiVersion: v1
kind: ConfigMap
metadata:
  name: anaconda-config
data:
  POSTGRES_HOST: anaconda-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: anaconda_db
  POSTGRES_USER: anaconda_user
  PUBLIC_WEB_URL: https://anaconda.godny.tech
  PUBLIC_API_URL: https://api.anaconda.godny.tech
  CORS_ALLOWED_ORIGINS: https://anaconda.godny.tech
  TELEGRAM_BOT_USERNAME: anaconda_mvp_bot
  TELEGRAM_WEBHOOK_URL: https://api.anaconda.godny.tech/api/webhook/telegram
  TELEGRAM_USE_POLLING: "false"
  EMAIL_IMAP_HOST: imap.yandex.ru
  EMAIL_IMAP_PORT: "993"
  EMAIL_IMAP_SSL: "true"
