apiVersion: v1
kind: ConfigMap
metadata:
  name: anaconda-config
data:
  POSTGRES_HOST: anaconda-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: anaconda_db
  POSTGRES_USER: anaconda_user
  PUBLIC_WEB_URL: https://anaconda.godny.tech
  PUBLIC_API_URL: https://api.anaconda.godny.tech
