apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: anaconda
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
images:
  - name: 127.0.0.1:30500/anaconda/api
    newTag: git-477accd
    digest: sha256:0e4e47fdf4f28b8337d3e94094ed171e737f9e37be593d9bd124b65a394f2733
  - name: 127.0.0.1:30500/anaconda/web
    newTag: git-477accd
    digest: sha256:3f02d8b77ff1b7b548ac1a87bb5687485e5c9c49d64d97b4116baff9515c3d54
