apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: barber
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 512Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: anaconda
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 750m
        memory: 768Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: kolos
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 200m
        memory: 256Mi
      default:
        cpu: 1000m
        memory: 1Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: ai-platform
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 250m
        memory: 512Mi
      default:
        cpu: 2000m
        memory: 4Gi

