apiVersion: apps/v1
kind: Deployment
metadata:
  name: barber-frontend
  labels:
    app.kubernetes.io/name: barber-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: barber-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: barber-frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: frontend
          image: 127.0.0.1:30500/barber/frontend:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: https://barber.godny.tech/api
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 750m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: barber-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: barber-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http

