apiVersion: apps/v1
kind: Deployment
metadata:
  name: barber-redis
  labels:
    app.kubernetes.io/name: barber-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: barber-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: barber-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: redis
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: barber-redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: barber-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis

