controller:
  ingressClassResource:
    name: nginx
    default: true
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 768Mi

